# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://chetandhembre.github.io
baseurl: 
title: Dream Code
author: Chetan Dhembre
description: Personal blog and resume
avatar: profile.png
email: chetandhembre@gmail.com
github: chetandhembre
twitter: ichetandhembre
instgram: chetandhembre 
google_analytics: UA-69391421-1